### ISSUE TITLE
internal flag is broken

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#176]
https://github.com/abhinav/doc2go/blob/f3f59ad6ccc833bf0b7d87658fffaaef1149b244/help/default.txt#L24-L25

internal defaults to false:

https://github.com/abhinav/doc2go/blob/f3f59ad6ccc833bf0b7d87658fffaaef1149b244/flags.go#L80

but running this:

~~~
doc2go std
~~~

still creates internal entries:

~~~
_site\internal\abi\index.html
~~~

and still creates internal HTML:

~~~html
<tr>
   <td><a href="go/internal/typeparams">go/internal/typeparams</a></td>
   <td></td>
</tr>
~~~

**Comment by 3052** [comment]
looks like the problem is here:

https://github.com/abhinav/doc2go/blob/f3f59ad6ccc833bf0b7d87658fffaaef1149b244/internal/html/render.go#L370-L376


misses items like these:

~~~
{RelativePath:crypto/internal/alias Synopsis:Package alias implements memory aliasing tests.}
{RelativePath:crypto/internal/poly1305 Synopsis:Package poly1305 implements Poly1305 one-time message authentication code as specified in https://cr.yp.to/mac/poly1305-20050329.pdf.}
{RelativePath:go/internal/gccgoimporter Synopsis:Package gccgoimporter implements Import for gccgo-generated object files.}
{RelativePath:go/internal/gcimporter Synopsis:Package gcimporter implements Import for gc-generated object files.}
{RelativePath:go/internal/srcimporter Synopsis:Package srcimporter implements importing directly from source files rather than installed packages.}
{RelativePath:go/internal/typeparams Synopsis:}
~~~

**Comment by abhinav** [comment]
Hey, I'll have a chance to provide a more complete response later, but if this is about the fact that doc2go generates internal packages even without the flag: that's intentional. 

The internal flag only changes whether internal packages are listed in package indexes.
This is desirable: if a type refers to an internal package, we still want to be able to see its documentation. 

I'm open to making this customizable, but I think the current behavior as the default makes sense.
(And the documentation could be clearer about this, I suppose.)

**Comment by 3052** [comment]
the current flag hides some internal packages, but not others. that is my issue. here:

https://pkg.go.dev/std

`go/internal/gcimporter` is not listed, but Doc2Go does list it incorrectly:

~~~html
    <tr>
        <td><a href="go/internal/gcimporter">go/internal/gcimporter</a></td>
        <td>Package gcimporter implements Import for gc-generated object files.</td>
      </tr>
~~~

**Comment by 3052** [comment]
https://github.com/abhinav/doc2go/pull/177

**Comment by abhinav** [comment]
Ah, I see. Thanks for the PR. Looking now.
