### ISSUE TITLE
No non-test Go files. Skipping.

### ISSUE THREAD

**Issue by mschneider82** [abhinav/doc2go#54]
i have a large mono repo with many subpackages

it just finds 10 packages and the rest is skipped without a reason:

repo/badgerdb] No non-test Go files. Skipping.
repo/metrics] No non-test Go files. Skipping.
repo/configuration] No non-test Go files. Skipping.
...

even the package folder is ok and imported by many applications:
```
metrics
├── doc.go
├── example_test.go
├── new.go
├── new_test.go
├── README.md
└── registry.go
````

**Comment by mschneider82** [comment]
on the second run if finds nearly all packages (i tried -debug), just 1 is skipped with the above error

**Comment by abhinav** [comment]
Hi, @mschneider82, thanks for reporting!
Upon digging, this happens because doc2go was incorrectly relying on go/packages' CompiledGoFiles attribute, instead of GoFiles.  I'll push a fix.

You can verify the before/after by setting GOCACHE to a temporary directory:

```
GOCACHE=$(mktemp -d) doc2go ./...
```

With the current version, this will reliably reproduce the "skipping" behavior.
